
import 'package:get/get.dart';

class LanguageTranslations extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
        "createYourAccount": "Create your\nAccount",
        "otpVarification":"Otp\nVerification",
        "phoneNumber":"Phone number",
        "enter":"ENTER",
        "signInText":"Already have account?",
        "signInText2":"Sign in",
        "verificationText":"We have sent the code verification to your mobile number",
        "getOtp":"GET OTP",
        "resendText":"Dont recieve otp?",
        "resendText2":"Resend otp",
        "nameText":"What's your\nName",
        "fullName":"Full name",
        "helloSignIn":"Hello\nSign in!",
        "signUpText":"Dont have account?",
        "signUpText2":"Sign up",
        "email":"Email",
        "licensenumber":"License Number",
        "vehiclenumber":"Vehicle Number",
        "newtext":"New",
        "outfordelivery":"OUT FOR DELIVERY",
        "ongoing":"Ongoing",
        "newOrder":"New Order",
        "orderdetails":"ORDER DETAILS",
        "orderlist":"ORDER LIST",
        "omr":"OMR",
        "qty":"Qty",
        "delivereydate":"Delivery Date",
        "deliverytime":"Delivery Time",
        "locatiion":"Location",
        "viewmap":"View Map",
        "accept":"ACCEPT",
        "cancel":"CANCEL",
        "total":"Total",
        "cancelorder":"CANCEL ORDER",
        "delivered":"DELIVERED",
        "selectreasonforcancelorder":"Select Reason for Cancel Order",
        "customernotavailableathome":"Customer not available at home",
        "locationnotclear":"Location not clear",
        "otherreason":"Other reason",
        "ok":"OK",
        "type":"Type",
        "orderstatus":"Order Status",
        "orderdeliveredsuccesfully":"Order Delivered Successfully",
        "orderStatus0":"Order Placed",
        "orderStatus1":"Order confirmed",
        "orderStatus2":"Order on the way",
        "orderStatus3":"Order processing",
        "orderStatus4":"Order delivered",
        "orderStatus5":"Order cancelled",
        "ordercancelled":"Order Cancelled",
        "reason":"Reason",
        "notdelivered":"Not Delivered",
        "paymentMethod":"Payment method",
        "confirm":"Confirm",
        "payment":"Payment",
        "language":"Language",
        "profile":"Profile",
        "orderHistory":"Order History",
        "signOut":"Sign out",
        "address":"Address",
        "save":"SAVE",
        "orderDate":"Order date",
        "deliveredOn":"Delivered on",
        "john":"John Smith",
        "requiredField":"This field is required",
        "validEmail":"Please enter a valid email address",
        "wait":"Please wait....🕚",
        "approve":"We will approve your request soon!📋",
        "comeBack":"Come back for future updates👍",
        "verified":"Successfully verified",
        "invalidOtp":"Invalid OTP",
        "error":"Error",
        "ok":"OK",
        "verificationFailed":"phoneNumber Verification Failed please check phoneNumber",
        "submit":"SUBMIT",
        "number":"Number cannot be empty",
        "ongoingOrder":"Ongoing Order",
        "refill":"Refill",
        "noNew":"No New Orders Found",
        "noOngoing":"No Ongoing Orders Found",
        "noOrderHistory":"No Order History Found",
        "order":"Order"
      },
    'ar_OM': {
        "createYourAccount": "التسجيل",
        "otpVarification":"تآكيد رمز التفعيل",
        "phoneNumber":"رقم النقال",
        "enter":"ادخل",
        "signInText":"لديك حساب مسجل؟",
        "signInText2":"تسجيل الدخول",
        "verificationText":"لقد تم ارسال رمز التحقق الى رقمك",
        "getOtp":"احصل على رمز التحقق",
        "resendText":"لم تستلم رمز التحقق؟",
        "resendText2":" إعادة ارسال",
        "nameText":"الاسم",
        "fullName":"الاسم الكامل",
        "helloSignIn":"مرحبا تسجيل الدخول!",
        "signUpText":"لايوجد لديك حساب؟",
        "signUpText2":" اشترك",
        "email":"البريد الالكتروني",
        "licensenumber":"رقم الرخصة",
        "vehiclenumber":"رقم المركبة",
        "newtext":"اسطوانة جديدة",
        "ongoing":"جاري",
        "newOrder":"طلب جديد",
        "orderdetails":"تفاصيل الطلب",
        "orderlist":"قائمة الطلبات",
        "omr":"ر.ع",
        "qty":"العدد",
        "delivereydate":"تاريخ التوصيل",
        "deliverytime":"وقت التوصيل",
        "locatiion":"الموقع",
        "viewmap":"معاينة الخريطة",
        "accept":"موافق",
        "cancel":"الغاء",
        "total":"المجموع",
        "cancelorder":"الغاء الطلب",
        "delivered":"تم التوصيل",
        "selectreasonforcancelorder":"اخبرنا سبب الإلغاء",
        "customernotavailableathome":"العميل غير متواجد في المنزل",
        "locationnotclear":"الموقع غير واضح",
        "otherreason":"أسباب أخرى",
        "ok":"تم",
        "type":"النوع",
        "orderstatus":"حالة الطلب",
        "orderdeliveredsuccesfully":"تم توصيل الطلب بنجاح",
        "ordercancelled":"تم الغاء الطلب",
        "reason":"السبب",
        "notdelivered":"لم يتم التوصيل",
        "paymentMethod":"طريقة الدفع",
        "confirm":"تآكيد",
        "payment":"الدفع",
        "language":"اللغة",
        "profile":"ملف الشخصي",
        "orderHistory":"تاريخ الطلب",
        "signOut":"تسجيل خروج",
        "address":"العنوان",
        "save":"حفظ",
        "orderStatus0":"تم الطلب",
        "orderStatus1":"تم تاكيد الطلب",
        "orderStatus2":"اطلب على الطريق",
        "orderStatus3":"معالجة الطلب",
        "orderStatus4":"أجل تسليم",
        "orderStatus5":"تم الغاء الأمر او الطلب",
        "orderDate":"تاريخ الطلب",
        "deliveredOn":"تم التوصيل في",
        "john":"جون سميث",
        "requiredField":"هذه الخانة مطلوبه",
        "validEmail":"يرجى إدخال عنوان بريد إلكتروني صالح",
        "wait":"من فضلك انتظر .... 🕚",
        "approve":"سنوافق على طلبك قريبًا! 📋",
        "comeBack":"أعود للحصول على التحديثات المستقبلية👍",
        "verified":"تم التحقق بنجاح",
        "invalidOtp":"رمز التحقق غير صالح",
        "error":"خطأ",
        "ok":"موافق",
        "verificationFailed":"فشل التحقق من رقم الهاتف ، يرجى التحقق من رقم الهاتف",
        "submit":"إرسال",
        "number":"لا يمكن أن يكون الرقم فارغًا",
        "ongoingOrder":"طلب مستمر",
        "refill":"اعادة تعبئه",
        "noNew":"لم يتم العثور على طلبات جديدة",
        "noOngoing":"لم يتم العثور على أوامر جارية",
        "noOrderHistory":"لم يتم العثور على محفوظات الطلبات",
        "order":"ترتيب"
    },
  };
}